#!/bin/bash
keyring="./keyring"
if [[ ! -d "$keyring" ]]
then
    mkdir "$keyring"
    chmod 700 "$keyring"
fi
opcion=$(zenity --list --title="Gestión de claves públicas" --column="Opción" 1 "Ver clave" 2 "Buscar claves" 3 "Importar clave" 4 "Exportar clave")

case $opcion in
    1)
        archivo=$(zenity --file-selection --title="Selecciona clave pública")
        if [[ -n "$archivo" ]]
	then
        	zenity --text-info --title="Contenido de la clave" --filename="$archivo"
	else
		zenity --error --text="Falta la clave"
        fi
        ;;
    2)
        carpeta=$(zenity --file-selection --directory --title="Carpeta para buscar")
        resultados=$(find "$carpeta" -type f \( -name "*.pem" -o -name "*.pub" -o -name "*_public.pem" \))
		zenity --text-info --title="Claves encontradas" --text="$resultados"
        ;;
    3)
        archivo=$(zenity --file-selection --title="Selecciona clave a importar a $keyring")
        if [[ -n "$archivo" ]]
	then
            cp "$archivo" "$keyring/"
            chmod 600 "$keyring/$(basename "$archivo")"
            zenity --info --text="Clave importada en $keyring"
        fi
        ;;
    4)
        archivo=$(zenity --file-selection --title="Selecciona clave del keyring")
        carpeta=$(zenity --file-selection --directory --title="Carpeta de destino")
        if [[ -n "$archivo" && -n "$carpeta" ]]
	then
            cp "$archivo" "$carpeta/"
            zenity --info --text="Clave exportada a $carpeta"
        fi
        ;;
esac
