#!/bin/bash
opcion=$(zenity --list --title="Cifrado asimétrico híbrido" --column="Opción" 1 "Cifrar" 2 "Descifrar")

case $opcion in
    1)
        archivo=$(zenity --file-selection --title="Archivo a cifrar")
        clave_aes=$(zenity --file-selection --title="Archivo .bin de clave AES")
        clave_rsa=$(zenity --file-selection --title="Clave pública RSA (.pem)")
        carpeta=$(zenity --file-selection --directory --title="Carpeta de salida")
        nombre=$(zenity --entry --title="Nombre archivo cifrado" --text="Introduce nombre de salida")
        if [[ -n "$archivo" && -n "$clave_aes" && -n "$clave_rsa" && -n "$carpeta" && -n "$nombre" ]]
	then
            IV=$(openssl rand -hex 16)
            openssl enc -aes-256-cbc -pbkdf2 -salt -in "$archivo" -out "$carpeta/$nombre.enc" -K "$(xxd -p "$clave_aes" | tr -d '\n')" -iv "$IV"
            openssl rsautl -encrypt -pubin -inkey "$clave_rsa" -in "$clave_aes" -out "$carpeta/$nombre.aes.enc"
            echo "$IV" > "$carpeta/$nombre.iv"
            zenity --info --text="Archivo cifrado correctamente:\n$carpeta/$nombre.enc"
        else
            zenity --error --text="Faltan datos para cifrar"
        fi
        ;;
    2)
        archivo=$(zenity --file-selection --title="Archivo a descifrar")
        clave_rsa=$(zenity --file-selection --title="Clave privada RSA (.pem)")
        clave_aes_enc=$(zenity --file-selection --title="Archivo .aes.enc de clave AES")
        carpeta=$(zenity --file-selection --directory --title="Carpeta de salida")
        nombre=$(zenity --entry --title="Nombre archivo descifrado" --text="Introduce nombre de salida")
        iv_file=$(zenity --file-selection --title="Archivo .iv")
        if [[ -n "$archivo" && -n "$clave_rsa" && -n "$clave_aes_enc" && -n "$carpeta" && -n "$nombre" && -n "$iv_file" ]]
	then
            IV=$(cat "$iv_file")
            openssl rsautl -decrypt -inkey "$clave_rsa" -in "$clave_aes_enc" -out "$carpeta/$nombre.bin"
            openssl enc -d -aes-256-cbc -pbkdf2 -in "$archivo" -out "$carpeta/$nombre" -K "$(xxd -p "$carpeta/$nombre.bin" | tr -d '\n')" -iv "$IV"
            rm "$carpeta/$nombre.bin"
            zenity --info --text="Archivo descifrado correctamente:\n$carpeta/$nombre"
        else
            zenity --error --text="Faltan datos para descifrar"
        fi
        ;;
esac
